insert into category (name, description) values ('morbi', 'nisi vulputate nonummy maecenas tincidunt lacus');
insert into category (name, description) values ('eleifend quam', 'parturient montes nascetur ridiculus mus');
insert into category (name, description) values ('odio', 'elementum nullam varius nulla facilisi cras');
insert into category (name, description) values ('viverra pede', 'luctus ultricies eu nibh quisque id');
insert into category (name, description) values ('ipsum primis', 'montes nascetur ridiculus mus etiam');
insert into category (name, description) values ('ipsum', 'et commodo vulputate justo');
insert into category (name, description) values ('diam in', 'semper interdum mauris ullamcorper');
insert into category (name, description) values ('congue diam', 'primis in faucibus');
insert into category (name, description) values ('praesent blandit', 'suscipit a feugiat et eros');
insert into category (name, description) values ('eu felis', 'elementum pellentesque quisque porta volutpat erat');

insert into product (name, description, price, quantity, categoryid) values ('tristique fusce', 'ipsum ac tellus', 68.34, 6, 2);
insert into product (name, description, price, quantity, categoryid) values ('purus', 'magna ac consequat metus sapien ut', 12.08, 89, 1);
insert into product (name, description, price, quantity, categoryid) values ('justo', 'est donec odio', 36.66, 36, 6);
insert into product (name, description, price, quantity, categoryid) values ('eu sapien', 'aliquam erat volutpat in congue etiam justo', 55.46, 33, 7);
insert into product (name, description, price, quantity, categoryid) values ('interdum mauris', 'gravida sem praesent', 42.3, 4, 7);
insert into product (name, description, price, quantity, categoryid) values ('convallis', 'at vulputate vitae nisl aenean', 4.43, 78, 3);
insert into product (name, description, price, quantity, categoryid) values ('posuere', 'ut odio cras mi pede', 6.02, 56, 8);
insert into product (name, description, price, quantity, categoryid) values ('ultrices', 'neque duis bibendum morbi', 78.71, 29, 9);
insert into product (name, description, price, quantity, categoryid) values ('donec diam', 'nec dui luctus rutrum', 83.59, 70, 10);
insert into product (name, description, price, quantity, categoryid) values ('nec', 'malesuada in imperdiet', 70.02, 47, 7);
insert into product (name, description, price, quantity, categoryid) values ('et', 'tincidunt eget tempus vel pede morbi', 69.2, 28, 5);
insert into product (name, description, price, quantity, categoryid) values ('penatibus', 'proin leo odio porttitor', 9.61, 28, 6);
insert into product (name, description, price, quantity, categoryid) values ('luctus', 'parturient montes nascetur ridiculus mus vivamus', 91.98, 31, 6);
insert into product (name, description, price, quantity, categoryid) values ('aliquet massa', 'cras mi pede malesuada in imperdiet', 94.45, 27, 2);
insert into product (name, description, price, quantity, categoryid) values ('donec vitae', 'sit amet diam in', 66.13, 23, 9);
insert into product (name, description, price, quantity, categoryid) values ('nisi volutpat', 'pretium quis lectus', 50.83, 66, 5);
insert into product (name, description, price, quantity, categoryid) values ('platea dictumst', 'ut rhoncus aliquet pulvinar sed nisl nunc', 67.17, 70, 6);
insert into product (name, description, price, quantity, categoryid) values ('turpis', 'sit amet sem fusce consequat nulla', 90.0, 46, 2);
insert into product (name, description, price, quantity, categoryid) values ('nisi vulputate', 'malesuada in imperdiet et', 35.61, 28, 2);
insert into product (name, description, price, quantity, categoryid) values ('odio', 'id massa id nisl venenatis', 36.12, 92, 3);
insert into product (name, description, price, quantity, categoryid) values ('fringilla rhoncus', 'elit ac nulla sed', 38.62, 51, 4);
insert into product (name, description, price, quantity, categoryid) values ('nunc', 'imperdiet et commodo vulputate justo', 25.61, 70, 10);
insert into product (name, description, price, quantity, categoryid) values ('aenean sit', 'magna vestibulum aliquet ultrices erat tortor sollicitudin', 48.13, 74, 3);
insert into product (name, description, price, quantity, categoryid) values ('lobortis', 'orci nullam molestie nibh in lectus', 56.87, 16, 1);
insert into product (name, description, price, quantity, categoryid) values ('id lobortis', 'condimentum id luctus nec molestie', 41.58, 16, 2);
insert into product (name, description, price, quantity, categoryid) values ('tortor duis', 'volutpat sapien arcu', 91.03, 43, 5);
insert into product (name, description, price, quantity, categoryid) values ('orci', 'nisl venenatis lacinia aenean', 4.36, 70, 8);
insert into product (name, description, price, quantity, categoryid) values ('platea', 'viverra pede ac', 63.33, 64, 2);
insert into product (name, description, price, quantity, categoryid) values ('vestibulum', 'nulla tempus vivamus in felis eu sapien', 98.91, 59, 5);
insert into product (name, description, price, quantity, categoryid) values ('nibh', 'sapien sapien non mi', 74.8, 13, 6);
insert into product (name, description, price, quantity, categoryid) values ('nibh fusce', 'neque libero convallis eget eleifend luctus ultricies', 66.7, 69, 8);
insert into product (name, description, price, quantity, categoryid) values ('congue vivamus', 'erat eros viverra eget congue eget semper', 16.4, 66, 4);
insert into product (name, description, price, quantity, categoryid) values ('in imperdiet', 'lorem ipsum dolor sit amet', 20.36, 27, 10);
insert into product (name, description, price, quantity, categoryid) values ('amet lobortis', 'rutrum at lorem integer', 93.82, 17, 9);
insert into product (name, description, price, quantity, categoryid) values ('consequat lectus', 'ultrices posuere cubilia curae', 65.12, 75, 4);
insert into product (name, description, price, quantity, categoryid) values ('sit', 'magna vulputate luctus cum sociis natoque penatibus', 36.22, 2, 1);
insert into product (name, description, price, quantity, categoryid) values ('leo odio', 'curae mauris viverra diam', 93.45, 10, 2);
insert into product (name, description, price, quantity, categoryid) values ('nunc nisl', 'nisl venenatis lacinia aenean sit', 14.65, 11, 1);
insert into product (name, description, price, quantity, categoryid) values ('aenean', 'sem duis aliquam convallis nunc', 81.25, 61, 5);
insert into product (name, description, price, quantity, categoryid) values ('at velit', 'est lacinia nisi venenatis tristique fusce', 63.12, 26, 7);
insert into product (name, description, price, quantity, categoryid) values ('lacus at', 'elementum ligula vehicula consequat morbi', 80.77, 88, 2);
insert into product (name, description, price, quantity, categoryid) values ('ante ipsum', 'vestibulum eget vulputate ut', 92.82, 96, 3);
insert into product (name, description, price, quantity, categoryid) values ('suscipit', 'donec odio justo sollicitudin', 30.17, 14, 6);
insert into product (name, description, price, quantity, categoryid) values ('amet', 'purus aliquet at feugiat', 71.83, 69, 1);
insert into product (name, description, price, quantity, categoryid) values ('sed magna', 'dui nec nisi volutpat eleifend donec', 55.09, 97, 2);
insert into product (name, description, price, quantity, categoryid) values ('sodales sed', 'quis libero nullam sit', 19.3, 57, 10);
insert into product (name, description, price, quantity, categoryid) values ('purus aliquet', 'sed tincidunt eu felis fusce posuere felis', 24.7, 47, 1);
insert into product (name, description, price, quantity, categoryid) values ('id', 'dolor morbi vel lectus in quam', 69.42, 8, 2);
insert into product (name, description, price, quantity, categoryid) values ('quisque', 'convallis duis consequat dui', 93.14, 69, 10);
insert into product (name, description, price, quantity, categoryid) values ('non interdum', 'interdum mauris ullamcorper purus sit', 2.45, 29, 9);
insert into product (name, description, price, quantity, categoryid) values ('nulla', 'iaculis justo in hac habitasse platea', 9.96, 98, 10);
insert into product (name, description, price, quantity, categoryid) values ('felis ut', 'suspendisse potenti in eleifend quam a odio', 79.14, 25, 2);
insert into product (name, description, price, quantity, categoryid) values ('etiam vel', 'sit amet diam in magna bibendum imperdiet', 10.87, 18, 5);
insert into product (name, description, price, quantity, categoryid) values ('mi', 'imperdiet nullam orci', 45.25, 69, 3);
insert into product (name, description, price, quantity, categoryid) values ('eget', 'nulla tellus in sagittis dui vel nisl', 44.12, 71, 4);
insert into product (name, description, price, quantity, categoryid) values ('vel', 'sed magna at nunc', 48.32, 58, 4);
insert into product (name, description, price, quantity, categoryid) values ('sed', 'volutpat sapien arcu sed augue aliquam', 32.02, 98, 10);
insert into product (name, description, price, quantity, categoryid) values ('justo etiam', 'erat tortor sollicitudin mi sit amet', 83.16, 60, 5);
insert into product (name, description, price, quantity, categoryid) values ('non', 'nulla dapibus dolor vel est', 53.52, 68, 6);
insert into product (name, description, price, quantity, categoryid) values ('tempor convallis', 'tincidunt nulla mollis', 67.53, 44, 2);
insert into product (name, description, price, quantity, categoryid) values ('mus vivamus', 'gravida nisi at nibh in hac', 19.63, 16, 3);
insert into product (name, description, price, quantity, categoryid) values ('interdum in', 'consequat lectus in est risus auctor sed', 47.98, 94, 4);
insert into product (name, description, price, quantity, categoryid) values ('metus', 'congue elementum in', 86.16, 89, 5);
insert into product (name, description, price, quantity, categoryid) values ('in congue', 'turpis eget elit sodales scelerisque', 64.23, 30, 5);
insert into product (name, description, price, quantity, categoryid) values ('est', 'nunc rhoncus dui vel sem', 27.99, 55, 5);
insert into product (name, description, price, quantity, categoryid) values ('integer', 'justo etiam pretium iaculis justo in hac', 88.99, 87, 7);
insert into product (name, description, price, quantity, categoryid) values ('ac leo', 'at nibh in', 77.55, 54, 9);
insert into product (name, description, price, quantity, categoryid) values ('id justo', 'phasellus sit amet erat nulla tempus', 64.06, 39, 2);
insert into product (name, description, price, quantity, categoryid) values ('vel nulla', 'augue quam sollicitudin vitae consectetuer eget', 58.74, 41, 9);
insert into product (name, description, price, quantity, categoryid) values ('consectetuer', 'id luctus nec molestie sed justo', 94.18, 67, 3);
insert into product (name, description, price, quantity, categoryid) values ('diam', 'felis fusce posuere felis sed', 26.92, 19, 3);
insert into product (name, description, price, quantity, categoryid) values ('scelerisque', 'odio condimentum id luctus nec molestie', 56.33, 92, 9);
insert into product (name, description, price, quantity, categoryid) values ('euismod', 'imperdiet et commodo', 44.05, 94, 10);
insert into product (name, description, price, quantity, categoryid) values ('morbi non', 'in ante vestibulum ante ipsum primis', 63.29, 78, 2);
insert into product (name, description, price, quantity, categoryid) values ('proin eu', 'ipsum integer a nibh in', 84.57, 100, 7);
insert into product (name, description, price, quantity, categoryid) values ('fusce', 'nibh ligula nec', 5.77, 88, 7);
insert into product (name, description, price, quantity, categoryid) values ('nulla tempus', 'purus eu magna vulputate luctus', 73.93, 69, 7);
insert into product (name, description, price, quantity, categoryid) values ('potenti cras', 'vitae nisl aenean lectus pellentesque eget', 84.26, 42, 1);
insert into product (name, description, price, quantity, categoryid) values ('sem duis', 'sagittis sapien cum', 73.1, 24, 7);
insert into product (name, description, price, quantity, categoryid) values ('lacinia sapien', 'aliquam non mauris morbi', 82.91, 51, 10);
insert into product (name, description, price, quantity, categoryid) values ('auctor sed', 'pede posuere nonummy', 38.04, 21, 6);
insert into product (name, description, price, quantity, categoryid) values ('diam nam', 'sagittis sapien cum sociis', 28.46, 76, 3);

insert into movement (type, quantity, categoryid, productid) values ('entrada', 100, 9, 36);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 84, 3, 30);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 29, 6, 61);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 37, 2, 39);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 44, 9, 78);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 85, 6, 69);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 14, 1, 71);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 19, 6, 38);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 96, 3, 1);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 49, 9, 73);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 17, 9, 71);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 27, 9, 46);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 68, 4, 16);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 31, 3, 75);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 68, 7, 22);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 55, 5, 16);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 47, 1, 18);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 24, 5, 29);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 69, 5, 31);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 34, 2, 61);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 72, 6, 4);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 14, 3, 53);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 88, 9, 30);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 48, 4, 40);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 19, 4, 21);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 47, 2, 13);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 45, 10, 62);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 94, 2, 17);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 74, 4, 50);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 62, 2, 19);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 99, 4, 12);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 76, 2, 8);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 43, 5, 15);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 78, 9, 10);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 96, 1, 7);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 96, 8, 78);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 91, 9, 17);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 86, 1, 66);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 50, 10, 42);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 89, 4, 73);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 56, 10, 44);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 93, 3, 63);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 16, 10, 69);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 45, 1, 50);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 21, 3, 21);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 11, 1, 15);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 72, 3, 23);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 13, 4, 56);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 9, 5, 5);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 56, 10, 3);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 26, 1, 17);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 17, 3, 34);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 19, 7, 49);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 4, 4, 2);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 76, 5, 24);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 31, 6, 4);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 21, 8, 41);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 49, 6, 68);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 86, 8, 47);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 40, 1, 56);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 66, 1, 8);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 17, 9, 18);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 62, 9, 15);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 56, 6, 18);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 83, 10, 19);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 22, 5, 19);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 47, 10, 78);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 52, 9, 35);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 61, 8, 71);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 29, 1, 68);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 13, 10, 32);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 32, 4, 45);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 93, 7, 81);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 63, 2, 43);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 13, 2, 76);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 42, 4, 16);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 41, 2, 47);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 77, 3, 28);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 95, 7, 19);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 21, 1, 12);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 26, 9, 78);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 57, 5, 67);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 46, 9, 74);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 84, 6, 77);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 33, 1, 50);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 14, 1, 29);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 65, 7, 38);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 25, 10, 75);
insert into movement (type, quantity, categoryid, productid) values ('entrada', 6, 1, 24);
insert into movement (type, quantity, categoryid, productid) values ('salida', 71, 8, 15);
insert into movement (type, quantity, categoryid, productid) values ('salida', 20, 3, 5);
insert into movement (type, quantity, categoryid, productid) values ('salida', 78, 10, 34);
insert into movement (type, quantity, categoryid, productid) values ('salida', 22, 6, 23);
insert into movement (type, quantity, categoryid, productid) values ('salida', 75, 4, 25);
insert into movement (type, quantity, categoryid, productid) values ('salida', 31, 2, 60);
insert into movement (type, quantity, categoryid, productid) values ('salida', 82, 3, 46);
insert into movement (type, quantity, categoryid, productid) values ('salida', 75, 5, 39);
insert into movement (type, quantity, categoryid, productid) values ('salida', 16, 5, 9);
insert into movement (type, quantity, categoryid, productid) values ('salida', 13, 9, 48);
insert into movement (type, quantity, categoryid, productid) values ('salida', 24, 5, 14);
insert into movement (type, quantity, categoryid, productid) values ('salida', 95, 9, 80);
insert into movement (type, quantity, categoryid, productid) values ('salida', 66, 2, 37);
insert into movement (type, quantity, categoryid, productid) values ('salida', 10, 6, 7);
insert into movement (type, quantity, categoryid, productid) values ('salida', 84, 4, 80);
insert into movement (type, quantity, categoryid, productid) values ('salida', 49, 8, 31);
insert into movement (type, quantity, categoryid, productid) values ('salida', 62, 5, 29);
insert into movement (type, quantity, categoryid, productid) values ('salida', 55, 8, 43);
insert into movement (type, quantity, categoryid, productid) values ('salida', 1, 10, 45);
insert into movement (type, quantity, categoryid, productid) values ('salida', 96, 6, 25);
insert into movement (type, quantity, categoryid, productid) values ('salida', 47, 9, 46);
insert into movement (type, quantity, categoryid, productid) values ('salida', 70, 5, 29);
insert into movement (type, quantity, categoryid, productid) values ('salida', 83, 8, 74);
insert into movement (type, quantity, categoryid, productid) values ('salida', 19, 6, 42);
insert into movement (type, quantity, categoryid, productid) values ('salida', 5, 6, 33);
insert into movement (type, quantity, categoryid, productid) values ('salida', 73, 1, 81);
insert into movement (type, quantity, categoryid, productid) values ('salida', 74, 10, 74);
insert into movement (type, quantity, categoryid, productid) values ('salida', 49, 5, 45);
insert into movement (type, quantity, categoryid, productid) values ('salida', 17, 8, 18);
insert into movement (type, quantity, categoryid, productid) values ('salida', 16, 9, 65);
insert into movement (type, quantity, categoryid, productid) values ('salida', 29, 2, 57);
insert into movement (type, quantity, categoryid, productid) values ('salida', 10, 8, 71);
insert into movement (type, quantity, categoryid, productid) values ('salida', 47, 4, 31);
insert into movement (type, quantity, categoryid, productid) values ('salida', 28, 8, 23);
insert into movement (type, quantity, categoryid, productid) values ('salida', 93, 5, 9);
insert into movement (type, quantity, categoryid, productid) values ('salida', 98, 2, 21);
insert into movement (type, quantity, categoryid, productid) values ('salida', 69, 6, 34);
insert into movement (type, quantity, categoryid, productid) values ('salida', 17, 5, 66);
insert into movement (type, quantity, categoryid, productid) values ('salida', 17, 8, 16);
insert into movement (type, quantity, categoryid, productid) values ('salida', 73, 10, 66);
insert into movement (type, quantity, categoryid, productid) values ('salida', 99, 6, 19);
insert into movement (type, quantity, categoryid, productid) values ('salida', 39, 7, 76);
insert into movement (type, quantity, categoryid, productid) values ('salida', 75, 7, 72);
insert into movement (type, quantity, categoryid, productid) values ('salida', 5, 2, 40);
insert into movement (type, quantity, categoryid, productid) values ('salida', 96, 9, 19);
insert into movement (type, quantity, categoryid, productid) values ('salida', 85, 8, 11);
insert into movement (type, quantity, categoryid, productid) values ('salida', 36, 8, 2);
insert into movement (type, quantity, categoryid, productid) values ('salida', 94, 5, 5);
insert into movement (type, quantity, categoryid, productid) values ('salida', 41, 6, 25);
insert into movement (type, quantity, categoryid, productid) values ('salida', 84, 2, 28);
insert into movement (type, quantity, categoryid, productid) values ('salida', 23, 9, 34);
insert into movement (type, quantity, categoryid, productid) values ('salida', 69, 6, 2);
insert into movement (type, quantity, categoryid, productid) values ('salida', 29, 6, 77);
insert into movement (type, quantity, categoryid, productid) values ('salida', 11, 9, 34);
insert into movement (type, quantity, categoryid, productid) values ('salida', 15, 2, 38);
insert into movement (type, quantity, categoryid, productid) values ('salida', 67, 4, 5);
insert into movement (type, quantity, categoryid, productid) values ('salida', 33, 4, 43);
insert into movement (type, quantity, categoryid, productid) values ('salida', 11, 7, 12);
insert into movement (type, quantity, categoryid, productid) values ('salida', 16, 3, 33);
insert into movement (type, quantity, categoryid, productid) values ('salida', 2, 6, 77);
insert into movement (type, quantity, categoryid, productid) values ('salida', 23, 10, 14);
insert into movement (type, quantity, categoryid, productid) values ('salida', 33, 8, 53);
insert into movement (type, quantity, categoryid, productid) values ('salida', 65, 9, 14);
insert into movement (type, quantity, categoryid, productid) values ('salida', 25, 1, 10);
insert into movement (type, quantity, categoryid, productid) values ('salida', 48, 5, 20);
insert into movement (type, quantity, categoryid, productid) values ('salida', 32, 6, 43);
insert into movement (type, quantity, categoryid, productid) values ('salida', 89, 8, 80);
insert into movement (type, quantity, categoryid, productid) values ('salida', 39, 5, 76);
insert into movement (type, quantity, categoryid, productid) values ('salida', 47, 9, 9);
insert into movement (type, quantity, categoryid, productid) values ('salida', 24, 1, 66);
insert into movement (type, quantity, categoryid, productid) values ('salida', 46, 10, 43);
insert into movement (type, quantity, categoryid, productid) values ('salida', 66, 8, 7);
insert into movement (type, quantity, categoryid, productid) values ('salida', 18, 9, 33);
insert into movement (type, quantity, categoryid, productid) values ('salida', 75, 5, 46);
insert into movement (type, quantity, categoryid, productid) values ('salida', 33, 2, 13);
